VueDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create_article, name='create_article'),
    path('detail/<int:article_pk>/', views.detail, name='detail'),
    path('update/<int:article_pk>/', views.update_article, name='update_article'),
    path('comment/<int:article_pk>/', views.comment_create, name='comment'),
    path('comment/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
    path('hashtags/', views.hashtag_list, name="hashtag_list")
]

articles/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Hashtag(models.Model):
    content = models.TextField(unique=True)
    detect = models.CharField(max_length=500, default="alert alert-light")
    def __str__(self):
        return self.content

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=5000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    hashtags = models.ManyToManyField(Hashtag, blank=True)
    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("articles:detail", kwargs={"article_pk": self.pk})

class Comment(models.Model):
    content = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return self.content


    

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):    
    class Meta:
        model = Article
        fields = ('title', 'content', )

class CommentForm(forms.ModelForm):    
    class Meta:
        model = Comment
        fields = ("content",)

articles/views.py
from django.views.decorators.http import require_POST
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponseBadRequest
from django.core.serializers.json import DjangoJSONEncoder
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .forms import ArticleForm, CommentForm
from .models import Article, Comment, Hashtag
from .serializers import CommentSerializer, ArticleSerializer, HashtagSerializer
import json

# Create your views here.
def index(request):
    vue_articles = json.dumps(ArticleSerializer(Article.objects.all(), many=True).data)
    context = {'vue_articles':vue_articles,}
    return render(request, 'articles/index.html', context)

def create_article(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid:
            article = form.save()
            for word in article.content.split(): 
                if word.startswith('#'): 
                    hashtag, created = Hashtag.objects.get_or_create(content=word)
                    article.hashtags.add(hashtag) 
            return redirect(article)
    else:
        form = ArticleForm()
    context = {'form':form, }
    return render(request, 'articles/form.html', context)

def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comments_json = json.dumps(CommentSerializer(article.comment_set.all(), many=True).data)
    context = {'article':article, 'comments_json':comments_json}
    return render(request, 'articles/detail.html', context)

def update_article(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():            
            article = form.save()
            return redirect(article)
    else:
        form = ArticleForm(instance=article)        
    context = {'form':form,}
    return render(request, 'articles/form.html', context)

@api_view(['POST'])
def comment_create(request, article_pk):
    if request.is_ajax():
        form = CommentForm(request.data)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article_id = article_pk
            comment.save()
            comment = json.dumps(CommentSerializer(comment).data)
            return JsonResponse(comment, status=201, safe=False)
        else:
            return JsonResponse({'message': 'fail'}, status=202)
    else:
        return HttpResponseBadRequest(401)
        
@require_POST
def comment_delete(request, comment_pk):
    if request.is_ajax():
        comment = get_object_or_404(Comment, pk=comment_pk)
        comment.delete()
        return JsonResponse({"message": "삭제되었습니다."}, status=204)
    return HttpResponseBadRequest(401)

def hashtag_list(request):
    hashtags = json.dumps(HashtagSerializer(Hashtag.objects.all(), many=True).data)
    articles = json.dumps(ArticleSerializer(Article.objects.all(), many=True).data)
    context = {'hashtags':hashtags, 'articles':articles,}
    return JsonResponse(context, status=200)

VueDjango/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
  <div id="nav" class="container">
  <div class="col-3">
    <input width="50px" @input="onInput" @keydown.enter="click_search_list(search)" type="text" v-model="search">
    <input class="mb-2" type="button" value="검색">
    <br>
    <div class="border" v-if="search_list.length">
      <div 
        v-for="search_item in search_list"
        :class="search_item.detect"
        v-on:mouseover="changebgcolor(search_item)"
        v-on:mouseout="originalcolor(search_item)"
        @click="click_search_list(search_item)"
        style="cursor:pointer">          
          {% if request.resolver_match.url_name != 'index'  %}
            <a class="w-100 h-100" href="{% url 'articles:index' %}" @click="back_hash(search_item)">[[ search_item.content ]]</a>
          {% else %}
            [[ search_item.content ]]
          {% endif %}
      </div>
    </div>
  </div>    
  </div>
  <div class="container" id="app">
  {% block content %}
  
  {% endblock content %}
  </div>
  
  

  
  <script>
    const STORAGE_KEY = 'vue-article'
    const STORAGE_KEY2 = 'vue-hashtag'
    const STORAGE_KEY3 = 'vue-search'
    const STORAGE_KEY4 = 'back'
    const backStorage = {
      fetch: function () {
        return JSON.parse(localStorage.getItem(STORAGE_KEY4))
      },
      save: function (back) {
        localStorage.setItem(STORAGE_KEY4, back)
      }
    }
    const searchStorage = {
      fetch: function () {
        return JSON.parse(localStorage.getItem(STORAGE_KEY3) || '[]')
      },
      save: function (search_list) {
        localStorage.setItem(STORAGE_KEY3, JSON.stringify(search_list))
      }
    }
    const articleStorage = {
      fetch: function () {
        return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]')
      },
      save: function (articles) {
        localStorage.setItem(STORAGE_KEY, articles)
      }
    }
    const hashtagStorage = {
      fetch: function () {
        return JSON.parse(localStorage.getItem(STORAGE_KEY2) || '[]')
      },
      save: function (hashtag) {
        localStorage.setItem(STORAGE_KEY2, hashtag)
      }
    }
    
    const baseApp = new Vue({
      delimiters: ["[[", "]]"],
      el: '#nav',
      data: {
        search: '',
        search_list: [],
        hashtags: [],      
      },
      mounted: function () {
        axios.get('{% url "articles:hashtag_list" %}')
          .then(res =>{
            hashtagStorage.save(res.data.hashtags)
            articleStorage.save(res.data.articles)
          })
        if (backStorage.fetch() === true) {
          return
        }
        this.hashtags = hashtagStorage.fetch()
        localStorage.removeItem(STORAGE_KEY3)
      },
      methods:{
        back_hash: function (seha) {
          backStorage.save(true)
          searchStorage.save(hashtagStorage.fetch().filter(item => item.id != seha)[0])
        },
        onInput: function(e) {
          if (!this.search) return this.search_list = []
          this.search_list= hashtagStorage.fetch().filter(search_hashtag => search_hashtag.content.startsWith(this.search))
        },
        click_search_list: function(click_search) {
          searchStorage.save(click_search)           
          this.search = ''
          this.search_list= []
          if ('{{ request.resolver_match.url_name }}' === 'index') {
            app.article_filter()
            this.search_list=[]
          }          
        },
        changebgcolor: function(SI) {
          SI.detect = "alert alert-primary"          
        },
        originalcolor: function(SI) {
          SI.detect = "alert alert-light"
        }
      }
    })
  </script>
  {% block java %}
  
  {% endblock java %}
</body>
</html>

articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load make_link %}

{% block content %}


<h1>{{ article.pk }}번 글의 Detail </h1>
<a @click="back_method" href="{% url 'articles:index' %}">back</a><br>
<b> 제목 : {{ article.title }} </b>
<p> 내용 : {{ article|hashtag_link|safe }}</p>
<p> 작성일시 : {{ article.created_at }} </p>
<p> 수정일시 : {{ article.updated_at }} </p>
<hr>

<br>
<div v-for="com_json in comments" :key="com_json.pk">
  <b>[[ com_json.content ]]</b>
  <p>[[ com_json.created_at ]]</p>
  <button @click="comment_delete(com_json.id)">삭제</button>
  <hr>
</div>
<br>


<input type="text" v-model="content" @keydown.enter="comment_create">
<button @click="comment_create">뷰버튼</button>

{% endblock content %}

{% block java %}
<script>
  const app = new Vue({
    delimiters: ["[[", "]]"],
    el: '#app',
    data: {
      content: '',
      comments: {{ comments_json|safe }}
    },
    methods: {
      back_method: function (seha) {
        backStorage.save(true)
        searchStorage.save(hashtagStorage.fetch().filter(item => item.id != seha)[0])
      },
      comment_create: function (e) {
        var postData = {content: this.content,}
        axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest'
        axios.defaults.xsrfCookieName = 'csrftoken'
        axios.defaults.xsrfHeaderName = 'X-CSRFToken'
        axios.post(`{% url 'articles:comment' article.pk %}`, postData)
          .then(response => {
            this.content=''
            if (response.data.length != undefined ) {              
              this.comments.unshift(JSON.parse(response.data))
            }
          })        
      },
      comment_delete: function (e) {
        axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest'
        axios.defaults.xsrfCookieName = 'csrftoken'
        axios.defaults.xsrfHeaderName = 'X-CSRFToken'
        axios.post(`{% url 'articles:comment_delete' 123456 %}`.replace('123456', e))
          .then(response => {
            this.comments = this.comments.filter(content => content.id !== e)
          })
      }
    }
  })
</script>
{% endblock java %}

articles/templates/articles/form.html
{% extends 'base.html' %}

{% block content %}
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="제출">
  </form>
{% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">뷰 테스트</h1>
  <a href="{% url 'articles:create_article' %}">글생성</a>
  <hr>
  <div v-for="article in vue_articles">
    <a :href="url" @click="mouseIn(article.id)">[[ article.title ]]</a><br>
    <a style="cursor:pointer" class="text-primary" @click="hashtag_search(hashtag)" v-for="hashtag in article.hashtags">[[ hashtag|capitalize ]]</a>
    <hr>
  </div>
  
{% endblock content %}

{% block java %} 
  <script>
    const app = new Vue({
      el: '#app',
      delimiters: ["[[", "]]"],
      data: {      
        vue_articles: {{ vue_articles|safe }},
        url: '',
        search: '',
        search_list: [],
      },
      mounted: function () {
        this.vue_articles = articleStorage.fetch()
        if (backStorage.fetch() === true) {
          backStorage.save(false)
          this.search_list = []
          this.article_filter()
        }
        localStorage.removeItem(STORAGE_KEY3)
      },
      methods: {
        hashtag_search: function(seha) {
          searchStorage.save(hashtagStorage.fetch().filter(item => item.id != seha)[0])
          this.article_filter()
        },
        mouseIn: function(e) {
          this.url = `{% url 'articles:detail' 123456 %}`.replace('123456', e)
        },        
        article_filter: function() {  
          if (searchStorage.fetch() === '#') {
            this.vue_articles = articleStorage.fetch()
            localStorage.removeItem(STORAGE_KEY3)
            return
          }
          this.vue_articles= articleStorage.fetch().filter(articles => articles.hashtags.some(hashtag => searchStorage.fetch().id))
          localStorage.removeItem(STORAGE_KEY3)
          this.search_list = []
        },
        
      },
      filters: {
        capitalize: id => {
          if (id.length === 0) return
          return hashtagStorage.fetch().filter(item => item.id != id)[0].content
          }
      },

    })
  </script>
{% endblock java %}